Scn_Settings As screen:
    Fill: =RGBA(237, 237, 237, 1)
    LoadingSpinner: =LoadingSpinner.Controls
    LoadingSpinnerColor: =gblAppColors.Primary_BlueGrey
    OnVisible: |-
        =//Enable Loading Spinner
        Set(VarLoadSpinner,true);
        
        
        //Disable Loading Spinner
        Set(VarLoadSpinner,false);

    cmp_SideNav_Scn_Settings As cmp_SideNav:
        Default: ="Settings"
        Y: =68

    cmp_TopBar_Settings As cmp_TopBar:
        ZIndex: =2

    Grp_Btn_Import_TestContact As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =5

        Btn_Nav_Settings_Import_TestContact As button:
            Align: =Align.Left
            BorderColor: =varAppStyles.Button_Save.BorderColor
            DisabledBorderColor: =varAppStyles.Button_Save.DisabledBorderColor
            DisabledFill: =varAppStyles.Button_Save.DisabledFill
            Fill: =varAppStyles.Button_Save.Fill
            FocusedBorderColor: =varAppStyles.Button_Save.FocusedBorderColor
            FocusedBorderThickness: =2
            Font: =varAppStyles.Button_Save.Font
            Height: =99
            HoverBorderColor: =varAppStyles.Button_Save.HoverBorderColor
            HoverColor: =varAppStyles.Button_Save.HoverColor
            HoverFill: =varAppStyles.Button_Save.HoverFill
            OnSelect: |-
                =Clear(Col_ImportContactList);
                Clear(Col_ImportContactList_Outcome);
                Navigate(Scn_ImportContactList)
            PaddingLeft: =80
            PaddingRight: =10
            PressedBorderColor: =varAppStyles.Button_Save.PressedBorderColor
            PressedColor: =varAppStyles.Button_Save.PressedColor
            PressedFill: =varAppStyles.Button_Save.PressedFill
            Text: |-
                ="Import
                Lab Contacts"
            Width: =215
            X: =843
            Y: =386
            ZIndex: =3

        Icn_Settings_Import_TestContact As icon.Phonebook:
            Color: =RGBA(255, 255, 255, 1)
            DisplayMode: =DisplayMode.View
            Height: =46
            Icon: =LookUp(colSidebarMenu, Value="Contact",Icon)
            Width: =46
            X: =861
            Y: =412
            ZIndex: =4

    Grp_Btn_Update_LabOffice As group:
        Height: =5
        Width: =5
        X: =20
        Y: =20
        ZIndex: =7

        Btn_Nav_Settings_UpdateLabOffice As button:
            Align: =Align.Left
            BorderColor: =varAppStyles.Button_Save.BorderColor
            DisabledBorderColor: =varAppStyles.Button_Save.DisabledBorderColor
            DisabledFill: =varAppStyles.Button_Save.DisabledFill
            Fill: =varAppStyles.Button_Save.Fill
            FocusedBorderColor: =varAppStyles.Button_Save.FocusedBorderColor
            FocusedBorderThickness: =2
            Font: =varAppStyles.Button_Save.Font
            Height: =99
            HoverBorderColor: =varAppStyles.Button_Save.HoverBorderColor
            HoverColor: =varAppStyles.Button_Save.HoverColor
            HoverFill: =varAppStyles.Button_Save.HoverFill
            OnSelect: =Launch(LookUp(Config_General,Title="ListURL_LabOffice",String_Value))
            PaddingLeft: =80
            PaddingRight: =10
            PressedBorderColor: =varAppStyles.Button_Save.PressedBorderColor
            PressedColor: =varAppStyles.Button_Save.PressedColor
            PressedFill: =varAppStyles.Button_Save.PressedFill
            Text: |-
                ="Update
                Lab Office"
            Width: =215
            X: =322
            Y: =386
            ZIndex: =5

        Icn_Settings_Update_LabOffice As icon.Phonebook:
            Color: =RGBA(255, 255, 255, 1)
            DisplayMode: =DisplayMode.View
            Height: =46
            Icon: =Icon.OfficeBuilding
            Width: =46
            X: =340
            Y: =412
            ZIndex: =6

    Grp_Btn_Nav_CapabilityList As group:
        Height: =5
        Width: =5
        X: =20
        Y: =20
        ZIndex: =9

        Btn_Nav_Settings_Nav_CapabilityList As button:
            Align: =Align.Left
            BorderColor: =varAppStyles.Button_Save.BorderColor
            DisabledBorderColor: =varAppStyles.Button_Save.DisabledBorderColor
            DisabledFill: =varAppStyles.Button_Save.DisabledFill
            Fill: =varAppStyles.Button_Save.Fill
            FocusedBorderColor: =varAppStyles.Button_Save.FocusedBorderColor
            FocusedBorderThickness: =2
            Font: =varAppStyles.Button_Save.Font
            Height: =99
            HoverBorderColor: =varAppStyles.Button_Save.HoverBorderColor
            HoverColor: =varAppStyles.Button_Save.HoverColor
            HoverFill: =varAppStyles.Button_Save.HoverFill
            OnSelect: =Launch(LookUp(Config_General,Title="ListURL_TestCapability",String_Value))
            PaddingLeft: =80
            PaddingRight: =10
            PressedBorderColor: =varAppStyles.Button_Save.PressedBorderColor
            PressedColor: =varAppStyles.Button_Save.PressedColor
            PressedFill: =varAppStyles.Button_Save.PressedFill
            Text: |-
                ="Capability
                List"
            Width: =215
            X: =322
            Y: =191
            ZIndex: =7

        Icn_Settings_Nav_CapabilityList As icon.Phonebook:
            Color: =RGBA(255, 255, 255, 1)
            DisplayMode: =DisplayMode.View
            Height: =46
            Icon: =LookUp(colSidebarMenu, Value="Capability",Icon)
            Width: =46
            X: =340
            Y: =217
            ZIndex: =8

    Grp_Btn_Nav_EquipmentList As group:
        Height: =5
        Width: =5
        X: =20
        Y: =20
        ZIndex: =11

        Btn_Nav_Settings_Nav_EquipmentList As button:
            Align: =Align.Left
            BorderColor: =varAppStyles.Button_Save.BorderColor
            DisabledBorderColor: =varAppStyles.Button_Save.DisabledBorderColor
            DisabledFill: =varAppStyles.Button_Save.DisabledFill
            Fill: =varAppStyles.Button_Save.Fill
            FocusedBorderColor: =varAppStyles.Button_Save.FocusedBorderColor
            FocusedBorderThickness: =2
            Font: =varAppStyles.Button_Save.Font
            Height: =99
            HoverBorderColor: =varAppStyles.Button_Save.HoverBorderColor
            HoverColor: =varAppStyles.Button_Save.HoverColor
            HoverFill: =varAppStyles.Button_Save.HoverFill
            OnSelect: =Launch(LookUp(Config_General,Title="ListURL_TestEquipment",String_Value))
            PaddingLeft: =80
            PaddingRight: =10
            PressedBorderColor: =varAppStyles.Button_Save.PressedBorderColor
            PressedColor: =varAppStyles.Button_Save.PressedColor
            PressedFill: =varAppStyles.Button_Save.PressedFill
            Text: |-
                ="Equipment
                List"
            Width: =215
            X: =843
            Y: =191
            ZIndex: =9

        Icn_Settings_Nav_EquipmentList As icon.Phonebook:
            Color: =RGBA(255, 255, 255, 1)
            DisplayMode: =DisplayMode.View
            Height: =46
            Icon: =LookUp(colSidebarMenu, Value="Equipment",Icon)
            Width: =46
            X: =861
            Y: =217
            ZIndex: =10

